#!/usr/bin/env bash
# Materialise placeholder file bodies for the rows seeded by
# `backend/migrations/0002_seed.sql`.
#
# The SQL seed inserts file metadata but no actual bytes — the FsStore can't
# return content that was never written.  This script creates a small
# stand-in for each seed file so that:
#   - GET /api/files/:id/download returns 200 (instead of 404)
#   - PDFs render in the inline `<object>` preview
#   - Office docs / images / videos at least download cleanly
#
# Idempotent: re-running overwrites the placeholders with the same content.
# Safe to invoke as part of `make dev` or right after `cargo run` on a fresh
# checkout.  Files are written **plaintext** because the seed rows carry
# `encrypted = false` — the download path won't run them through AES-GCM.
#
# Usage:
#   ./scripts/seed-bodies.sh                 # default ./backend/storage
#   STORAGE_ROOT=./backend/storage ./scripts/seed-bodies.sh
set -euo pipefail

STORAGE="${STORAGE_ROOT:-$(cd "$(dirname "$0")/../backend" && pwd)/storage}"
echo "Materialising seed bodies under: $STORAGE"

# IMPORTANT: the SQL seed in 0002_seed.sql stores `object_key` WITHOUT a
# bucket prefix (e.g. `contracts/2026-Q1/contract-A12.pdf`), so FsStore looks
# them up at `$STORAGE/<object_key>` — **not** `$STORAGE/<bucket>/<key>`.
# Newer uploads do include the bucket in the key, but the seed predates that
# convention.  Match what the seed actually says.
for d in \
    "$STORAGE/contracts/2026-Q1" \
    "$STORAGE/exports" \
    "$STORAGE/handbook" \
    "$STORAGE/media/workshop-photos" \
    "$STORAGE/archive" \
    "$STORAGE/templates" \
    "$STORAGE/budgets/2026" \
    "$STORAGE/vendors"; do
    mkdir -p "$d"
done

# Minimal one-page PDF.  Hand-crafted xref tables drift the moment the
# preamble length changes, so we let Python compute byte offsets instead —
# the resulting PDF passes pdf.js, Adobe Reader, and the macOS Preview.
# Python is already a dependency (`scripts/test-api.sh` requires it).
write_pdf() {
    local out="$1"
    local label="${2:-Seed placeholder}"
    python3 - "$out" "$label" <<'PYEOF'
import sys

out, label = sys.argv[1], sys.argv[2]

# Stream contents — display $label at the top-left of a normal A4 page.
content = f"BT /F1 24 Tf 60 760 Td ({label}) Tj ET\n".encode()
objects = [
    b"<</Type/Catalog/Pages 2 0 R>>",
    b"<</Type/Pages/Kids[3 0 R]/Count 1>>",
    b"<</Type/Page/Parent 2 0 R/MediaBox[0 0 595 842]/Contents 4 0 R/Resources<</Font<</F1 5 0 R>>>>>>",
    b"<</Length " + str(len(content)).encode() + b">>stream\n" + content + b"endstream",
    b"<</Type/Font/Subtype/Type1/BaseFont/Helvetica>>",
]

buf = bytearray()
buf += b"%PDF-1.4\n%\xe2\xe3\xcf\xd3\n"  # binary marker keeps strict readers happy
offsets = []
for i, body in enumerate(objects, 1):
    offsets.append(len(buf))
    buf += f"{i} 0 obj\n".encode() + body + b"\nendobj\n"

xref_start = len(buf)
buf += f"xref\n0 {len(objects)+1}\n".encode()
buf += b"0000000000 65535 f \n"
for off in offsets:
    buf += f"{off:010d} 00000 n \n".encode()
buf += f"trailer<</Size {len(objects)+1}/Root 1 0 R>>\nstartxref\n{xref_start}\n%%EOF\n".encode()

with open(out, "wb") as f:
    f.write(buf)
PYEOF
}

write_pdf "$STORAGE/contracts/2026-Q1/contract-A12.pdf"           "contract-A12"
write_pdf "$STORAGE/contracts/2026-Q1/contract-A13-amendment.pdf" "contract-A13 amendment"
write_pdf "$STORAGE/handbook/onboarding-2026.pdf"                 "Onboarding 2026"
write_pdf "$STORAGE/handbook/policy-handbook-v4.pdf"              "Policy handbook v4"

# Plain-text placeholders — small enough that download is instant but big
# enough to be obviously "not the real document".
printf 'EmployeeID,Name,Department,Email\n1001,Anong Klin,HR,anong@acme.go.th\n1002,Wisanu Tan,Legal,wisanu@acme.go.th\n' \
    > "$STORAGE/exports/employee-roster.csv"

# Office docs — write a real (if minimal) .docx / .xlsx zip so that the
# lazy preview-generator in `p1::get_preview` can actually hand it to
# LibreOffice and produce a PDF.  Plain-text bytes named `.docx` would
# fail conversion and the inspector would stay stuck on "Preview not
# available yet".
write_docx() {
    python3 - "$1" "$2" <<'PYEOF'
import sys, zipfile
out, label = sys.argv[1], sys.argv[2]
DOC = f"""<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:body>
    <w:p><w:r><w:t>{label}</w:t></w:r></w:p>
    <w:p><w:r><w:t>Seed placeholder generated by scripts/seed-bodies.sh — replace via /filehub/upload.</w:t></w:r></w:p>
  </w:body>
</w:document>"""
TYPES = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>
</Types>"""
RELS = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>
</Relationships>"""
with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED) as z:
    z.writestr("[Content_Types].xml", TYPES)
    z.writestr("_rels/.rels", RELS)
    z.writestr("word/document.xml", DOC)
PYEOF
}

write_xlsx() {
    python3 - "$1" "$2" <<'PYEOF'
import sys, zipfile
out, label = sys.argv[1], sys.argv[2]
SHEET = f"""<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
  <sheetData>
    <row r="1"><c r="A1" t="inlineStr"><is><t>{label}</t></is></c></row>
    <row r="2"><c r="A2" t="inlineStr"><is><t>Seed placeholder — replace via /filehub/upload</t></is></c></row>
  </sheetData>
</worksheet>"""
WORKBOOK = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"
          xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
  <sheets><sheet name="Sheet1" sheetId="1" r:id="rId1"/></sheets>
</workbook>"""
WB_RELS = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/>
</Relationships>"""
TYPES = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>
  <Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>
</Types>"""
ROOT_RELS = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/>
</Relationships>"""
with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED) as z:
    z.writestr("[Content_Types].xml", TYPES)
    z.writestr("_rels/.rels", ROOT_RELS)
    z.writestr("xl/workbook.xml", WORKBOOK)
    z.writestr("xl/_rels/workbook.xml.rels", WB_RELS)
    z.writestr("xl/worksheets/sheet1.xml", SHEET)
PYEOF
}

write_docx "$STORAGE/templates/NDA-template-v3.docx"        "NDA template (seed)"
write_xlsx "$STORAGE/budgets/2026/budget-q1-2026.xlsx"     "Q1-2026 budget (seed)"
write_xlsx "$STORAGE/vendors/vendor-list-2026.xlsx"        "Vendor list 2026 (seed)"

# 1×1 transparent PNG — tiniest valid image so the gallery view + inline
# preview both render without error.  Base64-decoded inline so the script
# stays one self-contained file.
printf 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII=' \
    | base64 -d > "$STORAGE/media/team-photo.jpg"

# Video / zip — bytes are nonsense but at least non-empty.  These file types
# have no inline preview anyway; the UI falls back to "Download to view".
printf 'Placeholder MP4 — replace with a real .mp4 via /upload.\n' \
    > "$STORAGE/media/kickoff-call.mp4"
printf 'Placeholder ZIP — replace with a real archive via /upload.\n' \
    > "$STORAGE/archive/archive-2025.zip"

# folder seed row (`workshop-photos`) is a directory tombstone — no blob
# needed, but mkdir above ensured the directory exists.

# Summary
n=$(find "$STORAGE" -type f | wc -l | tr -d ' ')
echo "✓ wrote placeholder bodies; storage tree has $n files total"
